apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.appNS }}
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: {{ .Values.serviceProtocol }}
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}